#smtp
spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_PROPERTIES_SMTP_STARTTLS_ENABLE}

#kafka
kafka.mail.topic.name=mail-registration
kafka.mail.topic.name.dlt=mail-registration.DLT
spring.kafka.consumer.group-id=mail-group
spring.kafka.consumer.group-id.dlt=mail-group-dlt
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}