spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml

kafka.email.topic.name=mail-registration
kafka.credentials.topic.name=auth-credentials

backend.url=${BACKEND_URL}

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
