jwt.signing.key=${JWT_SIGNING_KEY}
jwt.duration=86400000

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml

#kafka
kafka.credentials.topic.name=auth-credentials
spring.kafka.consumer.group-id=auth-service
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}