server:
  port: ${SERVER_PORT}

spring:
  application:
    name: auth-service

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
  client:
    service-url:
      defaultZone : ${EUREKA_URL}